version: "3"

services:
  db:
    container_name: pokemon-db
    image: mongo:6.0
    volumes:
      - poke-vol:/data/db
    ports:
      - 27017:27017
      # util con aplicaciones de multiples contenedores
      # Reinicia el contenedor si se apaga inesperadamente
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: mongoadmin
      MONGO_INITDB_ROOT_PASSWORD: mongoadmin
      # cuando se monta la imagen ejecuta este comando
    command: ["--auth"]
volumes:
  poke-vol:
    external: false
