version: "3"

services:
  db:
    container_name: ${MONGO_DB_NAME}
    image: mongo:6.0
    volumes:
      - poke-vol:/data/db
    ports:
      - 27017:27017
      # util con aplicaciones de multiples contenedores
      # Reinicia el contenedor si se apaga inesperadamente
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: ${MONGO_USERNAME}
      MONGO_INITDB_ROOT_PASSWORD: ${MONGO_PASSWORD}
      # cuando se monta la imagen ejecuta este comando
    command: ["--auth"]
volumes:
  poke-vol:
    external: false
